// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/movie.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Movie with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Movie) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Movie with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MovieMultiError, or nil if none found.
func (m *Movie) ValidateAll() error {
	return m.validate(true)
}

func (m *Movie) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return MovieMultiError(errors)
	}

	return nil
}

// MovieMultiError is an error wrapping multiple validation errors returned by
// Movie.ValidateAll() if the designated constraints aren't met.
type MovieMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MovieMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MovieMultiError) AllErrors() []error { return m }

// MovieValidationError is the validation error returned by Movie.Validate if
// the designated constraints aren't met.
type MovieValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MovieValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MovieValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MovieValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MovieValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MovieValidationError) ErrorName() string { return "MovieValidationError" }

// Error satisfies the builtin error interface
func (e MovieValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMovie.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MovieValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MovieValidationError{}

// Validate checks the field values on ListMovieRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMovieRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMovieRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMovieRequestMultiError, or nil if none found.
func (m *ListMovieRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMovieRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageSize() > 10 {
		err := ListMovieRequestValidationError{
			field:  "PageSize",
			reason: "value must be less than or equal to 10",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListMovieRequestMultiError(errors)
	}

	return nil
}

// ListMovieRequestMultiError is an error wrapping multiple validation errors
// returned by ListMovieRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMovieRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMovieRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMovieRequestMultiError) AllErrors() []error { return m }

// ListMovieRequestValidationError is the validation error returned by
// ListMovieRequest.Validate if the designated constraints aren't met.
type ListMovieRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMovieRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMovieRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMovieRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMovieRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMovieRequestValidationError) ErrorName() string { return "ListMovieRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListMovieRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMovieRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMovieRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMovieRequestValidationError{}

// Validate checks the field values on ListMovieResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMovieResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMovieResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMovieResponseMultiError, or nil if none found.
func (m *ListMovieResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMovieResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMovies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMovieResponseValidationError{
						field:  fmt.Sprintf("Movies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMovieResponseValidationError{
						field:  fmt.Sprintf("Movies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMovieResponseValidationError{
					field:  fmt.Sprintf("Movies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMovieResponseMultiError(errors)
	}

	return nil
}

// ListMovieResponseMultiError is an error wrapping multiple validation errors
// returned by ListMovieResponse.ValidateAll() if the designated constraints
// aren't met.
type ListMovieResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMovieResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMovieResponseMultiError) AllErrors() []error { return m }

// ListMovieResponseValidationError is the validation error returned by
// ListMovieResponse.Validate if the designated constraints aren't met.
type ListMovieResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMovieResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMovieResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMovieResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMovieResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMovieResponseValidationError) ErrorName() string {
	return "ListMovieResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMovieResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMovieResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMovieResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMovieResponseValidationError{}
